plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/*_schema.rb'
    - 'db/migrate/*'
    - 'config/application.rb'
    - 'Gemfile*'
    - 'app/views/**/*.jbuilder'
    - 'bin/*'
  NewCops: disable

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 15
  Exclude:
    - 'app/lib/*'

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 15
  Exclude:
    - 'app/lib/*'

Metrics/ClassLength:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/LetSetup:
  Enabled: false
